name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Node
    - uses: actions/checkout@v1
    - uses: comchangs/action-yarn@master
      with: 
        args: "yarn install; yarn build"
    - name: list dir
      run: ls -al
      
